# Generated by Django 3.2.24 on 2024-05-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='theme',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
