# Generated by Django 3.2.11 on 2024-05-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='theme',
            field=models.CharField(choices=[('Technical', 'Технический вопрос'), ('General', 'Общий вопрос'), ('Bug', 'Сообщение об ошибке'), ('Other', 'Другое')], max_length=20),
        ),
    ]
