# Generated by Django 4.1.4 on 2024-05-13 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzastore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='author',
            new_name='size',
        ),
    ]
